# wrangler.toml 
name = "sat-blog-worker"
main = "api/index.js"  # Pointing to the correct sub-folder
compatibility_date = "2024-01-01"

[[d1_databases]]
binding = "DB"  # Changed from sat_blog_db to DB to match c.env.DB in index.js
database_name = "sat-blog-db"
database_id = "56f22122-96cb-4e9a-a87a-7b04fce1951e"  

[vars]
ENVIRONMENT = "production"