# wrangler.toml 
name = "sat-blog-worker"
main = "api/index.js"
compatibility_date = "2024-01-01"

[[d1_databases]]
binding = "DB"
database_name = "sat-blog-db"
database_id = "7ad1bc42-7fbd-440a-92f7-0ccffa5cd50a"  

[vars]
ENVIRONMENT = "production"