# wrangler.toml 
name = "sat-blog-worker"
main = "api/index.js"
compatibility_date = "2024-01-01"

[[d1_databases]]
binding = "DB"
database_name = "sat-blog-db"
database_id = "bed149f5-f416-4832-b1ed-f32d8123052b"  

[vars]
ENVIRONMENT = "production"