# wrangler.toml 
name = "sat-blog-worker"
main = "api/index.js"
compatibility_date = "2024-01-01"

[[d1_databases]]
binding = "DB"
database_name = "sat-blog-db"
database_id = "db24459c-56f0-45c7-ac12-4f646acc1b5e"  

[vars]
ENVIRONMENT = "production"